Change version.
emspay/ems-online-oscommerce pull request #5
Opened 2020-10-06 12:37 UTC by LeasoftKonstantinShapoval

Add expanded error description.

2020-10-07 09:45 UTC, tiutiunnykleasoft requested changes
Could you fix these comments?

2020-10-07 09:45 UTC, tiutiunnykleasoft commented on includes/modules/payment/emspay_afterpay.php
> +        if ($emspay_order['transactions'][0]['reason']) {
At that moment we don't have a transaction array from the order.
Only the error array returns from API. 
In this and other files must be another error capturing condition using $ems_order['error']<...> instead of $ems_order['transactions']<...>

2020-10-07 09:45 UTC, tiutiunnykleasoft commented on includes/modules/payment/emspay_afterpay.php
>      if ( !is_array( $emspay_order ) or array_key_exists( 'error', $emspay_order ) or $emspay_order['status'] == 'error' ) {
We need to update the order status in OsCommerce using other values,
Actually we don't have an 'id' key in ems_order array if the order creation returns with error

2020-10-07 10:06 UTC, LeasoftKonstantinShapoval commented on includes/modules/payment/emspay_afterpay.php
> +        if ($emspay_order['transactions'][0]['reason']) {
if (array_key_exists('error', $emspay_order) && array_key_exists('value', $emspay_order['error']))
        $reason .= " " . $emspay_order['error']['value'];
      if (array_key_exists('reason', $emspay_order['transactions'][0]))
        $reason .= " " . $emspay_order['transactions'][0]['reason'];

I suggest this solution. Like KPL realisation.

2020-10-09 09:47 UTC, tiutiunnykleasoft approved these changes

2020-10-09 09:53 UTC, tiutiunnykleasoft commented on includes/modules/payment/emspay_afterpay.php
> +        if (array_key_exists('error', $emspay_order) && array_key_exists('value', $emspay_order['error']))
let's replace that and next if condition using ternary operator PHP7.0 like ??

Ex.:` reason = error ?? another_error ?? null;` 
where `error` is directly error from array.

2020-10-09 12:27 UTC, LeasoftKonstantinShapoval commented on includes/modules/payment/emspay_afterpay.php
> +        if (array_key_exists('error', $emspay_order) && array_key_exists('value', $emspay_order['error']))
$emspay_order['error']  ? $reason .= ' '.$emspay_order['error']['value'] : null
 || $emspay_order['transactions'][0]['reason'] ? $reason .= $emspay_order['transactions'][0]['reason'] : null;

Thats better?

2020-10-09 12:29 UTC, tiutiunnykleasoft commented on includes/modules/payment/emspay_afterpay.php
> +        if (array_key_exists('error', $emspay_order) && array_key_exists('value', $emspay_order['error']))
i think we can much find a better solution in that case :)

Hint: try to use '??' operator.

2020-10-09 12:31 UTC, tiutiunnykleasoft commented on includes/modules/payment/emspay_afterpay.php
> +        if (array_key_exists('error', $emspay_order) && array_key_exists('value', $emspay_order['error']))
Anyway, your solution is better now than was

2020-10-09 12:44 UTC, LeasoftKonstantinShapoval commented on includes/modules/payment/emspay_afterpay.php
> +        if (array_key_exists('error', $emspay_order) && array_key_exists('value', $emspay_order['error']))
Updated.

2020-10-09 12:53 UTC, tiutiunnykleasoft approved these changes
OK.

2020-10-12 08:42 UTC, merged